include:
  - board: nice_nano_v2
    shield: corne_dongle/left
    keymap: corne
    name: corne_left
    settings:
      - left.conf

  - board: nice_nano_v2
    shield: corne_dongle/right
    keymap: corne
    name: corne_right
    settings:
      - right.conf

  - board: nice_nano_v2
    shield: none
    keymap: dongle
    name: dongle
    settings:
      - dongle.conf